apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: another-ns
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: MONGO_INITDB_ROOT_USERNAME  # Changed "Key" to "key"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: MONGO_INITDB_ROOT_PASSWORD  # Changed "Key" to "key"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: another-ns
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
