apiVersion: apps/v1
kind: Deployment
metadata:
  name: napa-app
  namespace: another-ns
spec:
  selector:
    matchLabels:
      app: napa-app
  template:
    metadata:
      labels:
        app: napa-app
    spec:
      containers:
      - name: napa
        image: dapper01/napa:1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:  # Corrected to lowercase
              name: mongodb-secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:  # Corrected to lowercase
              name: mongodb-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
        livenessProbe:  # Corrected capitalization
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:  # Corrected capitalization
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 10  # Corrected capitalization
          periodSeconds: 10  # Corrected capitalization
          timeoutSeconds: 5  # Corrected capitalization
          failureThreshold: 3  # Corrected capitalization
---
apiVersion: v1
kind: Service
metadata:
  name: napa
  namespace: another-ns
spec:
  type: NodePort
  selector:
    app: napa-app
  ports:
  - port: 3000
    targetPort: 3000


